wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1634361986
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 13
      - 16
      4: 3.7.10
      5: 0.12.3
      8:
      - 5
misc:
  desc: null
  value:
    Normalization: None
    Rescaling: 1/255
train_cfg:
  desc: null
  value:
    base_lr: 0.8
    label_smoothing: 0.0
    log_dir: gs://ak-us-train/logs
    lr_schedule: half_cos
    model_dir: gs://ak-us-train/models
    momentum: 0.9
    optimizer: sgd
    total_epochs: 100
    warmup_epochs: 5
    warmup_factor: 0.1
    weight_decay: 5.0e-05
train_prep:
  desc: null
  value:
    augment_fn: default
    batch_size: 1024
    color_jitter: false
    crop_size: 224
    image_size: 512
    mixup: false
    num_classes: 1000
    resize_pre_crop: 256
val_prep:
  desc: null
  value:
    augment_fn: val
    batch_size: 1024
    color_jitter: false
    crop_size: 224
    image_size: 512
    mixup: false
    num_classes: 1000
    resize_pre_crop: 256
